"""Generates firmware/docs/pinouts/orangepi-4-pro.bdoc - the 40-pin header of
the Orange Pi 4 Pro, drawn in the same grammar as pinouts/pico2w.bdoc.

    python tools/opi4pro_pinout.py         rewrite the .bdoc

THE NUMBERS COME FROM THE BOARD. The table below is `gpio readall` (wiringOP
2.46) run on bibobox itself on 2026-09-07, which is the one source that cannot
disagree with the firmware actually on it: physical pin, the name wiringOP gives
it, its wPi number, and the sysfs GPIO number. The Orange Pi 4 Pro user manual
v1.4 (orangepi.net, OrangePi_4_Pro_A733_User-Manual_v1.4.pdf) is the cross-check
for the alternate functions.

WHY A GENERATOR IN tools/ AND NOT A HAND-EDITED .bdoc. The Pico pinout was
generated by a script in a scratchpad that no longer exists, so the day a pad
needed changing the choice was hand-editing 1100 lines of drawing commands or
rewriting the generator from the picture. This one is checked in.
"""
import io
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', 'firmware', 'docs', 'pinouts', 'orangepi-4-pro.bdoc')

# (physical, name, wPi, sysfs gpio). None where the pin is power or ground.
# Straight from `gpio readall`; do not "correct" it from a datasheet.
PINS = {
     1: ('3.3V',   None, None),   2: ('5V',     None, None),
     3: ('SDA.0',  0,  35),       4: ('5V',     None, None),
     5: ('SCL.0',  1,  34),       6: ('GND',    None, None),
     7: ('PWM0-2', 2,  356),      8: ('TXD.7',  3,  358),
     9: ('GND',    None, None),  10: ('RXD.7',  4,  359),
    11: ('PL9',    5,  361),     12: ('PL8',    6,  360),
    13: ('PL12',   7,  364),     14: ('GND',    None, None),
    15: ('PK9',    8,  329),     16: ('PL5',    9,  357),
    17: ('3.3V',   None, None), 18: ('PL2',    10, 354),
    19: ('MOSI.3', 11, 130),     20: ('GND',    None, None),
    21: ('MISO.3', 12, 131),     22: ('PD23',   13, 119),
    23: ('SCLK.3', 14, 129),     24: ('CE.0',   15, 140),
    25: ('GND',    None, None),  26: ('PE4',    16, 132),
    27: ('PB5',    17, 37),      28: ('PB4',    18, 36),
    29: ('PD0',    19, 96),      30: ('GND',    None, None),
    31: ('PD1',    20, 97),      32: ('PD5',    21, 101),
    33: ('PD2',    22, 98),      34: ('GND',    None, None),
    35: ('PD3',    23, 99),      36: ('PD6',    24, 102),
    37: ('PD4',    25, 100),     38: ('PD7',    26, 103),
    39: ('GND',    None, None),  40: ('PL13',   27, 365),
}

# What a name IS, for the colour and the caption. Same legend as the Pico page
# so the two read as one library.
def role(name):
    if name in ('3.3V', '5V'):
        return 'power'
    if name == 'GND':
        return 'ground'
    if name.startswith(('SDA', 'SCL')):
        return 'i2c'
    if name.startswith(('TXD', 'RXD')):
        return 'uart'
    if name.startswith(('MOSI', 'MISO', 'SCLK', 'CE')):
        return 'spi'
    if name.startswith('PWM'):
        return 'pwm'
    return 'gpio'

COLOUR = {
    'power': 'red', 'ground': 'gray', 'i2c': 'brCyan', 'uart': 'brBlue',
    'spi': 'magenta', 'pwm': 'brYellow', 'gpio': 'green',
}

# The ALTERNATE functions, by physical pin, from the user manual v1.4 (sections
# 3.15 and 3.17: the I2C, UART, SPI and PWM tables). Every one of these is OFF
# until its device-tree overlay is enabled in orangepi-config; the pin is a
# plain GPIO until then. The manual's own example calls pin 7 "PL4"; the board's
# wiringOP calls it PWM0-2 (gpio356). The board wins for numbering.
ALT = {
    3: 'I2C0 SDA', 5: 'I2C0 SCL',
    27: 'I2C1 SDA', 28: 'I2C1 SCL',
    19: 'SPI3 MOSI / I2C2 SDA', 23: 'SPI3 CLK / I2C2 SCL',
    21: 'SPI3 MISO / I2C3 SCL', 26: 'I2C3 SDA', 24: 'SPI3 CS0',
    8: 'UART7 TX', 10: 'UART7 RX',
    7: 'SPWM0-2', 29: 'PWM0-0', 33: 'PWM0-2', 35: 'PWM0-3', 37: 'PWM0-4',
    32: 'PWM0-5', 36: 'PWM0-6', 38: 'PWM0-7',
}

# The function a pin stands for, spelled out in the second cell: the alternate
# function where the manual lists one, otherwise what the pin plainly is.
def function(pin, name):
    r = role(name)
    if r == 'power':
        return 'USB-C rail' if name == '5V' else 'regulated out'
    if r == 'ground':
        return ''
    return ALT.get(pin, 'GPIO')

# ---- geometry: a 2x20 header, one row per pin pair --------------------------
W, H = 1280, 1000
ROW0, PITCH = 96, 40          # first row's top edge, and the row pitch
CELL_H = 34
BOARD_L, BOARD_R = 490, 790  # the header itself, drawn as the board's edge
NUM_W, CELL_W, GAP = 34, 132, 6

out = []
def emit(s=''):
    out.append(s)

def cell(x0, y0, colour, text, size=13):
    emit(f'setColor {colour}')
    emit(f'fillRect {x0} {y0} {x0 + CELL_W} {y0 + CELL_H}')
    emit('setColor black')
    emit(f'setTextSize {size}')
    emit('setTextAlign center')
    emit(f'drawText {x0 + CELL_W // 2} {y0 + 10} "{text}"')
    emit('setTextAlign left')

def number(x0, y0, text):
    emit('setColor white')
    emit(f'fillRect {x0} {y0} {x0 + NUM_W} {y0 + CELL_H}')
    emit('setColor black')
    emit('setTextSize 13')
    emit('setTextAlign center')
    emit(f'drawText {x0 + NUM_W // 2} {y0 + 10} "{text}"')
    emit('setTextAlign left')

emit('<Doc title="Orange Pi 4 Pro header" subtitle="the forty pins, as the board reports them" category="Boards" id="opi4proPinout">')
emit()
emit('<!--')
emit('  A PINOUT, and nothing else: the diagram. GENERATED by tools/opi4pro_pinout.py')
emit('  from `gpio readall` on the board; edit the script, not this file.')
emit('')
emit('  What this car has on which pin belongs on the page that includes this one:')
emit('')
emit('      <Include file="pinouts/orangepi-4-pro.bdoc"/>')
emit('-->')
emit()
emit(f'<Draw width="{W}" height="{H}">')
emit('# Orange Pi 4 Pro, 40-pin header. Left column odd pins, right column even,')
emit('# pin 1 at the top - the same way round as the board with its USB-C toward you.')
emit()
emit('setColor gray')
emit('setWidth 2')
emit(f'drawRect {BOARD_L} 66 {BOARD_R} 920')
emit('setColor brWhite')
emit('setWidth 1')
emit(f'drawRect {BOARD_L + 100} 40 {BOARD_L + 200} 66')
emit('setColor gray')
emit('setTextSize 12')
emit('setTextAlign center')
emit(f'drawText {(BOARD_L + BOARD_R) // 2} 44 "pin 1"')
emit(f'drawText {(BOARD_L + BOARD_R) // 2} 487 "Orange Pi 4 Pro"')
emit(f'drawText {(BOARD_L + BOARD_R) // 2} 505 "Allwinner A733"')
emit('setTextAlign left')
emit()

for row in range(20):
    y = ROW0 + row * PITCH
    yc = y + CELL_H // 2
    # ---- left: odd pin, cells run leftward from the board edge ----
    p = 2 * row + 1
    name, wpi, gpio = PINS[p]
    emit(f'# pin {p}')
    emit('setColor gray')
    emit(f'drawLine {BOARD_L - 14} {yc} {BOARD_L} {yc}')
    x = BOARD_L - 14 - NUM_W
    number(x, y, str(p))
    x -= GAP + CELL_W
    cell(x, y, COLOUR[role(name)], name)
    x -= GAP + CELL_W
    fn = function(p, name)
    if fn:
        cell(x, y, COLOUR[role(name)], fn)
    x -= GAP + CELL_W
    if gpio is not None:
        cell(x, y, 'white', f'gpio{gpio}   wPi {wpi}', 12)
    # ---- right: even pin, cells run rightward ----
    p = 2 * row + 2
    name, wpi, gpio = PINS[p]
    emit(f'# pin {p}')
    emit('setColor gray')
    emit(f'drawLine {BOARD_R} {yc} {BOARD_R + 14} {yc}')
    x = BOARD_R + 14
    number(x, y, str(p))
    x += NUM_W + GAP
    cell(x, y, COLOUR[role(name)], name)
    x += CELL_W + GAP
    fn = function(p, name)
    if fn:
        cell(x, y, COLOUR[role(name)], fn)
    x += CELL_W + GAP
    if gpio is not None:
        cell(x, y, 'white', f'gpio{gpio}   wPi {wpi}', 12)
    emit()

# ---- legend, the Pico page's colours plus the two this header adds ----------
emit('# legend')
lx = (W - 7 * 116 + 8) // 2
for key, label in (('power', 'power'), ('ground', 'ground'), ('gpio', 'GPIO'),
                   ('spi', 'SPI'), ('i2c', 'I2C'), ('uart', 'UART'), ('pwm', 'PWM')):
    emit(f'setColor {COLOUR[key]}')
    emit(f'fillRect {lx} 954 {lx + 108} 980')
    emit('setColor black')
    emit('setTextSize 12')
    emit('setTextAlign center')
    emit(f'drawText {lx + 54} 961 "{label}"')
    emit('setTextAlign left')
    lx += 116

emit('</Draw>')
emit()
emit('</Doc>')

with io.open(OUT, 'w', encoding='utf-8', newline='\n') as f:
    f.write('\n'.join(out) + '\n')
print('wrote', os.path.normpath(OUT), '-', len(out), 'lines')
